README.md, src/core/generateZodSchema.test.ts, src/core/jsDocTags.ts
This fixes the following two typos:
- minLenght -> minLength
- maxLenght -> maxLength
=> Typo fix: Lenght -> Length

README.md
Small correction on the README to clearly communicate what `@default` JSDoc directive does.
=> Docs fix: correct output from JSDoc `@default`

package.json, yarn.lock
It seemed easier to make a PR than to open an issue.  ts-to-zod [depends on tsutils directly to run](https://github.com/fabien0102/ts-to-zod/blob/main/src/core/jsDocTags.ts#L2), but it does not list tsutils in the dependencies of the project.  Because [the eslint TypeScript plugin does depend on tsutils](https://github.com/fabien0102/ts-to-zod/blob/main/yarn.lock#L779), this doesn't matter for ts-to-zod itself or any project using both ts-to-zod and that plugin, but any project not using eslint or the plugin will fail.  If you start a new, empty TypeScript project and add ts-to-zod (and nothing else) to it, running a command like `yarn ts-to-zod src/types/types.ts` will give:
```
Error: Cannot find module 'tsutils'
Require stack:
- …
```
=> Add tsutils to dependencies

src/core/generateZodSchema.test.ts, src/core/generateZodSchema.ts
Fix optional key on `Array<T>` syntax generation
#18
=> Fix optional array

example/heros.ts, example/heros.zod.ts, src/core/generateZodSchema.test.ts, src/core/generateZodSchema.ts
The `never` keyword was forgot and could be translated by `z.never()`
#24
=> feat: Add `never` support

package.json, src/core/jsDocTags.ts, yarn.lock
Apparently newest version of typescript are breaking some type comparisons, also this is more safe to have a stable version of typescript for this project (since we are using the compiler API).
#27
=> fix: Fix typescript version

src/core/generateZodSchema.test.ts, src/core/generateZodSchema.ts
Generate `z.date()` for `Date`
#31
=> feat: Add `Date` support

src/core/generateZodSchema.test.ts, src/core/generateZodSchema.ts
Fixes #36.  Handles single value unions how typescript handles them.
=> Fixes #36 | Allows for single value unions

src/core/generateZodSchema.test.ts, src/core/generateZodSchema.ts, src/core/jsDocTags.ts, src/utils/isNotNull.ts
Use `nullable()` when this is possible, this is solving half of the case from #54 and this is a bit more semantic.
=> Improve nullable

src/core/generateZodSchema.test.ts, src/core/generateZodSchema.ts
This PR fixes https://github.com/fabien0102/ts-to-zod/issues/65 
Feel free to refuse, my knowledge of the source code is very limited and I might not have all the perspective needed for this edit!
=> fix: union properties can be optional & nullable

babel.config.js, package.json, yarn.lock
`ts-jest` uses `tsc` to compile the source code before running the tests. As the project grows, it makes the tests slower and slower.
However, we don't really need to have type errors making the tests fail (in fact, it's even annoying for dev). There is a dedicated step for that in CI (`tsc --noEmit`) and our editor is generally configured to let us know when there is a type error.
Thus, we can ditch the type checking part and just compile the TS code into JS. This is what `babel-jest` does. Because it has less work to do, it is MUCH faster.
From my (quite performant) machine:
| Before | After |
|---|---|
| ![Before](https://user-images.githubusercontent.com/1094774/155885956-c758e3ed-70f5-4da4-b24d-6742ed3a6513.png) | ![After](https://user-images.githubusercontent.com/1094774/155885952-f4 …
=> Use babel-jest instead of ts-jest => FASTER tests 🏎️

package.json, src/core/generate.ts, src/core/generateZodSchema.test.ts, src/core/generateZodSchema.ts, yarn.lock
Currently a type with a `ReadonlyArray` field results in a circular dependency error.
```typescript
type Superman = {
weaknesses: ReadonlyArray<string>;
}
```
This PR adds support for `ReadonlyArray` by treating is as a normal zod array type, and adds a test to verify it works.
While testing I had to upgrade `ts-node` as I was getting this error:
https://stackoverflow.com/questions/72488958/false-expression-non-string-value-passed-to-ts-resolvetypereferencedirective
Happy to revert that bit if you don't want to upgrade that dependency :)
=> Adds support and test for ReadonlyArray

src/core/generateZodSchema.test.ts, src/core/generateZodSchema.ts
Transform `Set<string>` to `z.set(z.string())`
=> feat: add support for  `z.set`

package.json, yarn.lock
In cli.ts, `@oclif/errors` is imported, but it is not specified in the package dependencies. This makes the require call ambiguous and unsound, and produces this error when used in a project using yarn (with pnp):
```
Error: ts-to-zod tried to access @oclif/errors, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: @oclif/errors
Required by: ts-to-zod@npm:2.0.1
```
I assume the package was hoisted from the other `@oclif/*` packages, which can cause problems.
=> Add missing dependency on @oclif/errors

src/core/generate.ts, src/utils/traverseTypes.test.ts, src/utils/traverseTypes.ts
When working on another PR (https://github.com/fabien0102/ts-to-zod/pull/135), I found out that the current `getExtractedTypeNames` actually works, for most cases, "by mistake" because it's always run for all nodes in the file and types are always referenced in the file (so an error in one call would "self-heal" in a subsequent one).
I added some tests (see commit https://github.com/tvillaren/ts-to-zod/commit/9a2294ad0d1066c5722b4bc390f1befcb8870c63 for the tests added to the original file, some not passing) and refactored the method, everything is still green.
=> Refactoring of getExtractedTypeNames

src/core/generateZodSchema.test.ts, src/utils/traverseTypes.test.ts, src/utils/traverseTypes.ts
Various expressions where not taken into account when extracting types, thus leading to missing schema in output generation.
The two latter ones were implemented in https://github.com/fabien0102/ts-to-zod/pull/152 and https://github.com/fabien0102/ts-to-zod/pull/155 which I close to merge all fixes in this PR. 
The following helpers were not handled well: `["Array", "Promise",  "Omit", "Pick", "Record", "Partial", "Required"]`
when used in expressions such as 
```ts
export type Person = Partial<Villain>
```
This was added in https://github.com/fabien0102/ts-to-zod/pull/152 (closed) following this comment: https://github.com/fabien0102/ts-to-zod/pull/148#issuecomment-1664231249
This was added in https://github.com/fabien0102/ts-to-zod/pull/155 (closed)
Extracting types from expression such …
=> fix: Various type extractions

package.json, src/cli.ts, src/createConfig.ts, yarn.lock
prettier API is now async
see https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F#4-await-your-prettier-api-calls
=> core: upgrade to prettier v3

README.md, src/config.ts, src/config.zod.ts, ts-to-zod.config.js
config file had property `customJSDocFormats` while `generate` expected `customJSDocFormatTypes`
=> fix mismatch between config file and `generate` interface

.github/workflows/release-please.yaml
Following #171 which updated a few dependencies, the release process doesn't work anymore, as some packages now need a more recent node version (at least 16 from my local tests). 
As a consequence, the latest release was not pushed to NPM.
=> [Fix] Update node version in release flow

src/utils/traverseTypes.test.ts, src/utils/traverseTypes.ts
Type identifiers in extension clauses such as 
```ts
export interface Superhero extends Pick<Person, "name"> {
id: number,
};
```
were not extracted correctly thus leading to incomplete generations.
=> [Fix] Handle ExpressionWithTypeArguments in extend clause

src/core/generateZodSchema.test.ts, src/core/jsDocTags.ts
Implementing a solution to https://github.com/fabien0102/ts-to-zod/issues/188
This adds `nullable` to the modifiers when the property if the `@default` is `null`
=> feat: add null handling for @default tag

README.md, src/core/generateZodSchema.test.ts, src/core/generateZodSchema.ts, src/core/jsDocTags.ts
Fixes #193 — now JSDoc `@description` tags are applied to the Zod schema via `.describe()`
Helps for when Zod schemas are flowing further downstream into JSONSchemas and such :)
=> Add JSDoc @description support

src/core/generateZodSchema.test.ts, src/core/generateZodSchema.ts
Parenthesized or null is a valid TS types, but the current generator does not recognized this.
Fix #197
=> Parenthesized or null

src/cli.ts
This PR fixes #185.
Input file:
```
export interface IHaveUnknownDependency {
dep: UnknownDependency;
}
```
Actual output:
```
TypeError: Cannot read properties of undefined (reading 'jsonEnabled')
error Command failed with exit code 1.
```
Expected output:
```
»   Warning: Some schemas can't be generated due to direct or indirect missing 
»   dependencies:
»   iHaveUnknownDependencySchema
✔ Validating generated types
🎉 Zod schemas generated!
```
=> fix: context binding while processing errors

.github/workflows/tests.yaml, bin/dev, bin/run, package.json, src/cli.ts, src/core/generate.test.ts, yarn.lock
As described in https://github.com/fabien0102/ts-to-zod/issues/196, the `--help` flag didn't work anymore. 
Trying to add tests for `oclif`, I updated: 
- `@oclif/core` to latest (`3.26.0`)
- the `run` script, following the templates provided on oclif [website](https://oclif.io/docs/templates) (split into a `run` and `dev` ones)
- adding the `strategy` as `single` command for oclif ([documentation](https://oclif.io/docs/single_command_cli))
Running `ts-to-zod --help` will output the help information:
```
Generate Zod schemas from a Typescript file
USAGE
$ ts-to-zod  --all
$ ts-to-zod  --config example
$ ts-to-zod  --config example/person
$ ts-to-zod  --config config
ARGUMENTS
INPUT   input file (typescript)
OUTPUT  output file (zod schemas)
FLAGS
-a, --all                    Execute all …
```
=> Making --help flag work

src/cli.ts
Fixes #219
Haven't added tests as they would need to be at the CLI level. 
I've already spent quite some time trying to configure [@oclif/test](https://github.com/oclif/test) but I think we're missing some configuration on Oclif for the library (`@oclif/test` doesn't find the command)
=> fix: validation on same-file generation

.github/workflows/release-please.yaml
Adding `yarn build` as a step of the release process  because of the update of the `./bin/run.js` script
=> fix: release process needs build before publish

README.md
It fixes a trivial typo in README.md that I saw when reading it.
=> fix trivial typo in README.md

src/core/generateZodSchema.test.ts, src/core/jsDocTags.ts
Zod API requires that `.partial()` be applied to an object type _before_ `.nullable()` or `.optional()`.
=> fix: .partial() must be applied before .nullable() or .optional()

src/core/generateZodSchema.test.ts, src/core/jsDocTags.ts
Closes fabien0102/ts-to-zod#227 (or would if it wasn't already closed for inactivity)
Linked issue isn't mine, but I experienced (almost) the same thing. I have an interface that has a negative `minimum` value in the jsDoc
```ts
/**
* @minimum -45 @maximum 45
*/
angle: number | null
```
Which results in the error:
```
Error: Debug Failure. False expression: Negative numbers should be created in combination with createPrefixUnaryExpression
```
This PR prevents the error and adds a check a couple of the existing tests
=> FIX: handle negative minimum, maximum, and default values from jsDoc

README.md, package.json, src/core/generateZodSchema.test.ts, src/core/jsDocTags.ts, yarn.lock
As discussed in #144  the recent [Zod release v3.23](https://github.com/colinhacks/zod/releases/tag/v3.23.0) added support for `date`, `time` and `duration` string `@format` types and they are mentioned in [OpenAPI Formats Registry](https://spec.openapis.org/registry/format/) so we can now add support for them.
=> feat: add support for date, time and duration `@format` types

src/cli.ts
```javascript
const { spawn } = require("child_process");
const run = () => {
const command = "yarn";
const args = ["gen:example"];
const childProcess = spawn(command, args);
childProcess.stdout.on("data", (data) => {
console.log(`stdout: ${data}`);
});
childProcess.stderr.on("data", (data) => {
console.error(`stderr: ${data}`);
});
childProcess.on("close", (code) => {
if (code !== 0) {
console.error(`Command finished with code ${code}`);
} else {
console.log("Command finished successfully");
}
});
childProcess.on("error", (error) => {
console.error(`Execution error: ${error}`);
});
};
run();
``` 
In the previous execution method, the yarn gen:example command mistakenly routed validation messages to the standard error stream (stderr). Despite these messages being part of normal feedback …
=> fix!: update ora stream output

src/core/generateZodSchema.test.ts, src/core/generateZodSchema.ts
Fixes #273 
Non-identifier access type such as `Superman["a.b"]`, `Villain["0bla-test"]` are now handled
Also adds support for single quotes in index access type
=> fix: handling non-identifier index access type

src/utils/traverseTypes.test.ts, src/utils/traverseTypes.ts
=> fix: correctly extract types from index signature declaration

src/core/generateZodSchema.test.ts, src/core/generateZodSchema.ts
- When defining an object type within an object, it is inferred as any when converted to Zod.
- any is a supertype of object, necessitating a stronger assertion of the type.
- After generating the type, during validation, any includes optional, which leads to a mismatch with the original type.
- This issue is resolved by treating the object as record any. => z.record(z.any())
case 1: primitive object
``` typescript
export type Obj = object;
```
``` typescript
// Generated by ts-to-zod
import { z } from "zod";
export const objSchema = z.record(z.any());
```
case 2: object in object
```typescript
export interface ExampleObject {
result: object;
}
```
```typescript
// Generated by ts-to-zod
import { z } from "zod";
export const exampleObjectSchema = z.object({
result: z.record(z.any()),
}); …
```
=> feat: Improve Object Type Handling in Zod Conversion
